### ISSUE TITLE
2 evtest entries, 1 event

### ISSUE THREAD

**Issue by streff** [JamesGKent/rotary_volume#2]
Ignore the below, appears to be related to the number of steps. Currently need a half turn of the knob to get one event on volume_up or _down.   Leaving the issue up but closed for posterity.
Thanks.

~~Hi, not really an 'issue', more a documentation/user problem. I'm attempting to use this to control the volume on my rasPi zero, and having followed the steps listed to install your driver. I now have 2 entries in my evtest list ~~ 

~~Available devices:~~
~~/dev/input/event0:      Rotary Encoder Volume~~
~~/dev/input/event1:      rotary@4~~

~~Monitoring Rotary Encoder Volume yields no events while turning the knob, but rotary@4 shows my encoder working. What am I missing to tie the events generated by rotary@4 to the key events listed under Rotary Encoder Volume?~~
~~I had previously enabled a rotary encoder on its own prior to finding your repo, would I need to remove/undo any previous rotary encoder assertions? So far I've removed the original /boot/config.txt encoder entry and replaced it with a paste of yours (& moved pins to match on my pi). Any assistance appreciated.~~

**Comment by JamesGKent** [comment]
Hi there, having to turn halfway could be related to this bit:
https://github.com/JamesGKent/rotary_volume#optional-settings

where it has to see multiple steps before firing an event, you could reduce that setting and see if it helps.

**Comment by streff** [comment]
Just re-read that section, I misunderstood your choice of encoder & the impact it had - adjusted the setting and got it down to a manageable level, many thanks.

**Comment by JamesGKent** [comment]
No problem, if there is a way you think I could word it to make it clearer please let me know :)
