### ISSUE TITLE
On 4.14.78-4-osmc

### ISSUE THREAD

**Issue by BenSeventy9** [JamesGKent/rotary_volume#4]
All new 2019.05-1 install. Kernel 4.14.78-4-osmc.
I followed the instructions. what is wrong?

```
sudo make
make -C /lib/modules/4.14.78-4-osmc/build M= modules
make[1]: Entering directory '/usr/src/rbp2-headers-4.14.78-4-osmc'
make[2]: *** No rule to make target 'arch/arm/tools/syscall.tbl', needed by 'arch/arm/include/generated/uapi/asm/unistd-common.h'.  Stop.
arch/arm/Makefile:319: recipe for target 'archheaders' failed
make[1]: *** [archheaders] Error 2
make[1]: Leaving directory '/usr/src/rbp2-headers-4.14.78-4-osmc'
makefile:3: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by BenSeventy9** [comment]
I made a silly mistake by clone repo with root.

After testing with evtest I have to change devicename = "rotary@4" to rotary@5

Now it works!


Please make this changes in readme file:
from: "/etc/udef/rules.d/998-fix-input.rules"
to: "/etc/udev/rules.d/998-fix-input.rules"
from: "sudo ln -s /usr/src/rbp2-headers-$(uname -r) /lib/modules/$(uname -r/build"
to: "sudo ln -s /usr/src/rbp2-headers-$(uname -r) /lib/modules/$(uname -r)/build"

**Comment by JamesGKent** [comment]
Thank you, fixed in commit: https://github.com/JamesGKent/rotary_volume/commit/fe3d3d3a57cfc16059fcfee7fc6d2d457a4311c6
